let = input('digite algo: ')
print('o tipo primitivo desse valor é:', type(let))
print('Só tem espaço', let.isspace())
print('É um numero?', let.isnumeric())
print('é alfabetico?', let.isalpha())
print('é alfanumerico ?', let.isalnum())
print('esta em maisculula?', let.isupper())
print('esta em minuscula?', let.islower())
print('esta capitalizadaa?', let.istitle())